name: Publish Docker image
on:
  push:
    branches: [ master ]
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ildefra99/github-runner
          build_args: RUNNER_VERSION=2.277.1
          tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          build_args: RUNNER_VERSION=2.277.1
          repository: ilDefra99/github-runner-docker/github-runner
          tag_with_ref: true
